version: '3.9'

services:
  # backend:
  #   container_name: hack-server
  #   build:
  #     context: ./backend
  #     dockerfile: Dockerfile
  #   restart: always

  # proxy:
  #   depends_on:
  #     - backend
  #   container_name: hack-proxy
  #   build:
  #     context: ./frontend/
  #     dockerfile: Dockerfile
  #   ports:
  #     - "80:80"
  #   restart: always

  # telegram-bot:
  #   build:
  #     context: ./bot
  #     dockerfile: Dockerfile
  #   container_name: hack-tg-bot
  #   environment:
  #     TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
  #     ADMINS_CHAT_IDS: ${ADMINS_CHAT_IDS}
  #   command: python3 main.py
  #   depends_on:
  #     - database
  #   restart: always

  database:
    image: postgres:12.2-alpine
    restart: "no"
    container_name: hack-db
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"
    volumes:
      - hack-postgres-db:/var/lib/postgresql

  database-admin:
    image: dpage/pgadmin4
    container_name: hack-db-admin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${ADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${ADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"

  database-es:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.1
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
    ports:
      - "${ELASTIC_PORT}:${ELASTIC_PORT}"

volumes:
  hack-postgres-db: null
